GOOGLE_PROJECT_ID= # YOUR GCP PROJECT ID GOES HERE
CLOUD_RUN_SERVICE= # NAME OF YOUR CLOUD RUN SERVICE
REPOSITORY_NAME=# YOUR ARTIFACT REPOSITORY NAME GOES HERE
LOCATION_NAME=# YOUR GOOGLE CLOUD LOCATION GOES HERE

gcloud builds submit --tag $LOCATION_NAME-docker.pkg.dev/$GOOGLE_PROJECT_ID/$REPOSITORY_NAME/$CLOUD_RUN_SERVICE \
    --project=$GOOGLE_PROJECT_ID

gcloud run deploy $CLOUD_RUN_SERVICE \
    --image $LOCATION_NAME-docker.pkg.dev/$GOOGLE_PROJECT_ID/$REPOSITORY_NAME/$CLOUD_RUN_SERVICE \
    --platform managed \
    --region=$LOCATION_NAME \
    --allow-unauthenticated \
    --project=$GOOGLE_PROJECT_ID
